Repository yes1sir/Yes1sir-Client, pull requests merged in 2024-08, with the labels that each got.

#19 [ Style ] 나이 설정 페이지 구현
  src/components/Age/SelectDate.jsx
  src/components/common/Backspace.jsx
  src/pages/Age/Age.jsx
  src/pages/Target/Target.jsx
  src/styles/theme.js
Labels: 🎨 Style

#20 [ Style ] 홈페이지(진단 후) 페이지 구현
  src/components/HomeLogin/HomeLoginMbti.jsx
  src/components/HomeLogin/HomeLoginMbtiContent.jsx
  src/components/HomeLogin/HomeLoginTitle.jsx
  src/components/HomeLogout/HomeLogoutFix.jsx
  src/components/HomeLogout/HomeLogoutMbti.jsx
  src/components/common/HomeLoginBtn.jsx
  src/constants/HomeLogin/mbtiContent.js
  src/constants/HomeLogin/mbtiTitle.js
  src/pages/HomeLogin/HomeLogin.jsx
  src/pages/HomeLogout/HomeLogout.jsx
  src/styles/theme.js
  src/types/homeLoginBtnPropTypes.js
Labels: 🎨 Style

#23 [ Style ] 피부 진단 페이지 구현
  src/components/Target/SelectBox.jsx
  src/components/Test/ProgressIndicator.jsx
  src/constants/Target/selectTarget.js
  src/constants/Test/testList.js
  src/constants/Test/typeSum.js
  src/pages/Target/Target.jsx
  src/pages/Test/Test.jsx
  src/styles/theme.js
Labels: 🎨 Style

#24 [ Style ] 제품 추천 페이지 구현
  src/components/HomeLogin/HomeLoginMbti.jsx
  src/components/HomeLogin/HomeLoginMbtiContent.jsx
  src/components/Recommend/RecommendIngredient.jsx
  src/components/Recommend/RecommendItem.jsx
  src/components/Recommend/RecommendItemSection.jsx
  src/constants/Recommend/RecommendItemData.js
  src/constants/Recommend/avoidIngredient.js
  src/constants/Recommend/customIngredient.js
  src/constants/Recommend/typeData.js
  src/pages/HomeLogin/HomeLogin.jsx
  src/pages/Recommend/Recommend.jsx
  src/styles/theme.js
  src/types/Recommend/RecommendItemProps.js
Labels: 🎨 Style

#27 [ Style ] 제품 상세 페이지 구현 + 리뷰 작성 페이지 구현
  src/Router.jsx
  src/assets/svgs/star.svg
  src/components/Detail/DetailBottom.jsx
  src/components/Detail/DetailBuyBtn.jsx
  src/components/Detail/DetailMiddle.jsx
  src/components/Detail/DetailPurposeBtn.jsx
  src/components/Detail/DetailRecommendBtn.jsx
  src/components/Detail/DetailTop.jsx
  src/components/Detail/ReviewModal.jsx
  src/constants/Detail/detailProductData.js
  src/pages/Detail/Detail.jsx
  src/styles/theme.js
Labels: 🎨 Style

#30 [ Feat ] 피부 진단 결과 HomeLogin 페이지에 반영 구현
  src/pages/HomeLogin/HomeLogin.jsx
  src/pages/Test/Test.jsx
Labels: ✨ Feature

#33 [ style ] 로고 svg 교체
  src/assets/svgs/Logo.svg
  src/components/common/TopNav.jsx
Labels: 🎨 Style

#34 [ Style ] width 값 추가
  src/components/Login/LoginComponent.jsx
  src/components/common/Backspace.jsx
  src/pages/Age/Age.jsx
  src/pages/Target/Target.jsx
  src/pages/Test/Test.jsx
Labels: 🎨 Style

#36 [ Style ] 로그인 페이지 로고 및 Nav bar 안 보이도록 수정
  src/Roots.jsx
  src/components/Login/LoginTop.jsx
Labels: 🎨 Style

#38 [ Style ] TopNav 컴포넌트 style 수정
  src/components/common/TopNav.jsx
Labels: 🎨 Style

#40 [ Feat ] 추천 제품 조회 api 연결
  src/components/Recommend/RecommendItem.jsx
  src/components/Recommend/RecommendItemSection.jsx
  src/pages/Recommend/Recommend.jsx
  src/styles/theme.js
Labels: ✨ Feature

#42 [ Feat ] 추천 제품 조회 api 연결
  src/Router.jsx
  src/components/Detail/DetailRecommendBtn.jsx
  src/components/Detail/DetailTop.jsx
  src/components/Recommend/RecommendItem.jsx
  src/pages/Detail/Detail.jsx
Labels: ✨ Feature

#44 [ Feat ] 제품 리뷰 생성 api 연결
  package.json
  src/components/Detail/DetailBottom.jsx
  src/components/Detail/DetailBuyBtn.jsx
  src/components/Detail/DetailTop.jsx
  src/components/Detail/ReviewModal.jsx
  src/components/Login/LoginComponent.jsx
  src/pages/Age/Age.jsx
  src/pages/Detail/Detail.jsx
  src/pages/HomeLogin/HomeLogin.jsx
  src/styles/theme.js
  yarn.lock
Labels: ✨ Feature

#46 [ Feat ] 제품 리뷰 수정 + 삭제 api 연결
  src/components/Detail/DetailBottom.jsx
  src/components/Detail/DetailMiddle.jsx
  src/components/Detail/DetailTop.jsx
  src/components/common/HomeLoginBtn.jsx
  src/pages/Detail/Detail.jsx
  src/pages/HomeLogin/HomeLogin.jsx
  vite.config.js
Labels: ✨ Feature

#48 [ Feat ] vercel 설정 파일 추가
  vercel.json
Labels: ✨ Feature

#50 [ docs ] 백그라운드 이미지 절대경로로 수정
  src/pages/HomeLogin/HomeLogin.jsx
  src/pages/HomeLogout/HomeLogout.jsx
  src/pages/Recommend/Recommend.jsx
Labels: 📃 Docs
